---
- name: Extract dotfiles
  unarchive:
    src: dotfiles.tgz
    dest: '{{ ansible_user_dir }}'

- name: Create $HOME/bin directory
  file:
    path: '{{ ansible_user_dir }}/bin'
    state: directory

- name: Copy install_dots.sh to remote bin
  copy:
    src: install_dots.sh
    dest: '{{ ansible_user_dir }}/bin/install_dots.sh'
    mode: 0755

- name: Remove distro's bashrc and profile
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '{{ ansible_user_dir }}/.bashrc'
    - '{{ ansible_user_dir }}/.bash_profile'
    - '{{ ansible_user_dir }}/.profile'

- name: Install dotfiles
  shell: '{{ ansible_user_dir }}/bin/install_dots.sh'
  args:
    chdir: '{{ ansible_user_dir }}/.dotdeb'
