---
- hosts: gcn
  vars:
    flutter_dir: '/opt/flutter'
    ssh_custom_options:
      - "Include /etc/ssh/ssh_config.d/*"
    sshd_custom_options:
      - "AcceptEnv LANG"
  roles:
    - pre
    - dotfiles
    - golang
    - mikeanth_dev.flutter_web
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening

