---
- hosts: gcn
  vars:
    flutter_dir: '/opt/flutter'
    ssh_custom_options:
      - "Include /etc/ssh/ssh_config.d/*"
    sshd_custom_options:
      - "AcceptEnv LANG"
    caddy_environment_variables:
      caddy_systemd_capabilities_enabled: true
      caddy_systemd_network_dependency: true
      caddy_config: |
        org-y.noviana.xyz {
            log
            reverse_proxy http://localhost:8080 {
                header_up Host {http.request.host}
                header_up X-Real-IP {http.request.remote.host}
                header_up X-Forwarded-For {http.request.remote.host}
                header_up X-Forwarded-Port {http.request.port}
                header_up X-Forwarded-Proto {http.request.scheme}
            }
        }
  roles:
    - pre
    - dotfiles
    - golang
    - mikeanth_dev.flutter_web
    - { role: dev-sec.os-hardening, become: yes }
    - { role: dev-sec.ssh-hardening, become: yes }

