"sysAccountConfig":
  "initialSuperUsers":
  - "avatar": "iVBORw0KGgoAAAANSUhEUgAAAIAAAACAAQMAAAD58POIAAAABlBMVEUFLV4aVVvN7byTAAACp0lEQVR4nHyVTRKdOAyE5WHhzdR4lrMa5yZcJUfIDfDNwlE4Akun8opOSS1LZBOqHo/6gEY/bVkOAPiOR3gU2RXsgINNOoAnQZUG4LMDg6BJBTATdNkA3DtwEuxSAFwJDhEA5w5cBBANZAQoEA1EfzfDgEjHk6BCpOGjYDIMKJwJOvS1W8GHYUCFrwSH5oRTAfO3JI8RoBjYLRYwDP37P0G1v78JhoXhhVqgL6B1PN+gOohXrEohyggNbAE68y/ZDi9IgOL5HwvIQbAH6My/B6gELUBh/jWAHM9qQ4isRoXIamWIDG92iAzaIUVOGiZFDLQExQxRE8hXC+QF/rXn5Lcj/HpKGW+wDdlOVoWgDanXG+wizUsaGfX5Atsjsn+8XybxeH0W0Lt2tTnAR++NABumXp40gZV+6uUVYMetxrjNHuZT3Nr9ucCGsHI30BQc5lwCW29Yl+Ca0xAxCDSYoSecNgdMeWgAVAIfU4qbSnZSeUy9fngiKEn5Cv2s00Ioah8k4Gc3C9feY2DVMsQ6w4tiATC5ZnUksPSbeZVLxwrUze8EjWW7CFhvLdsIYG3YH+/vEDbqmAmslcf1coA2m+Z+NXyNEPvvU8p8g3a7lcWnT73Uiy+wnfKXOLBXy5A/Hv+9ru3Rf17gdG/HcflH4zCP15lgLnOvg2EhRXwopojPgBTxqqQIRz5SBL7YQoTz60iRNa5ChPXJDcb1e2wfEqN2BvDJ+gS4CJYI52ZF7kH2ckWI8ImN4EtoOPgWX6HvZUYcBOWTY9mAlTZ2GlvwkZx6e0oza88EXT/gO55tbLuthivBoXd9X+1cf3O1wUAxe/k0bMDkmnsScOIwDM1/skozAbcuhqH562aPS64Ehy1I3951C+KIGAF+AGvbZf4/FTy/AgAA//+mGQr4LxPDRAAAAABJRU5ErkJggg"
    "email": "superadmin@getcouragenow.org"
    "password": "superadmin"
  "jwt":
    "access":
      "expiry": 3600
      "secret": "some_jwt_access_secret"
    "refresh":
      "expiry": 360000
      "secret": "some_jwt_refresh_secret"
  "mailConfig":
    "copyright": "SOME_COPYRIGHT_MSG"
    "logoUrl": "https://via.placeholder.com/500x500?text=YOUR+LOGO+HERE"
    "productName": "SOME_PRODUCT"
    "senderMail": "gutterbacon@example.com"
    "senderName": "gutterbacon"
    "sendgrid":
      "apiKey": "SENDGRID_API_KEY_HERE"
    "smtp":
      "email": "winwisely268@gmail.com"
      "host": "smtp.gmail.com"
      "password": "blablabla"
      "port": 465
    "troubleContact": "SOME_TROUBLESHOOT_CONTACT_HERE"
  "sysCoreConfig":
    "cron":
      "backupDir": "./db/sys/sysaccount-backup"
      "backupSchedule": "@daily"
      "rotateSchedule": "@every 24h"
    "db":
      "dbDir": "./db/sys"
      "deletePrevious": true
      "encryptKey": "yYz8Xjb4HBn4irGQpBWulURjQk2XmwES"
      "name": "sysaccount.db"
      "rotationDuration": 1
  "sysFileConfig":
    "cron":
      "backupDir": "sysfiles-backup"
      "backupSchedule": "@daily"
      "rotateSchedule": "@every 24h"
    "db":
      "dbDir": "./db/sys"
      "deletePrevious": true
      "encryptKey": "A9bhbid5ODrKQVvd9MY17P5MZ"
      "name": "sysfiles.db"
      "rotationDuration": 1
  "unauthenticatedRoutes":
  - "/v2.sys_account.services.AuthService/Login"
  - "/v2.sys_account.services.AuthService/Register"
  - "/v2.sys_account.services.AuthService/ResetPassword"
  - "/v2.sys_account.services.AuthService/ForgotPassword"
  - "/v2.sys_account.services.AuthService/RefreshAccessToken"
  - "/v2.sys_account.services.AuthService/VerifyAccount"
  - "/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"
  - "/v2.sys_account.services.OrgProjService/ListOrg"
  - "/v2.sys_account.services.OrgProjService/ListNonSubscribedOrgs"
  - "/v2.sys_account.services.OrgProjService/ListProject"
  - "/v2.sys_account.services.OrgProjService/GetOrg"
  - "/v2.sys_account.services.OrgProjService/GetProject"
  - "/v2.mod_disco.services.SurveyService/ListDiscoProject"
  - "/v2.mod_disco.services.SurveyService/GetDiscoProject"
  - "/v2.mod_disco.services.SurveyService/GenTempId"
  - "/v2.mod_disco.services.SurveyService/ListSurveyProject"
  - "/v2.mod_disco.services.SurveyService/GetSurveyProject"
  - "/v2.mod_disco.services.SurveyService/NewSurveyUser"
