---
#- hosts: gcn
- hosts: default
  vars:
    #    flutter_dir: '/opt/flutter'
    ssh_custom_options:
      - "Include /etc/ssh/ssh_config.d/*"
    sshd_custom_options:
      - "AcceptEnv LANG"
    dotfiles_user_dir: "/home/ops"
    dotfiles_user_name: "ops"
#    unit_config:
#      - name: maintemplatev2
#        enabled: no
#        state: stopped
#        owner: "ops"
#        group: "ops"
#        path: "/home/ops/.config/systemd/user"
#        type: service
#        Unit:
#          Description: "Maintemplate v2"
#          Documentation: "https://github.com/getcouragenow/shared-doc"
#          Wants: network-online.target
#          After: network-online.target
#        Service:
#          Environment: "CONFIG_PASSWORD=blah"
#          ExecStart: "/home/ops/app/bin-all/maintemplatev2 -c /home/ops/app/config -e /home/ops/app/encrypted-config"
#          Restart: always
#          RestartSec: 12
#        Install:
#          WantedBy: default.target
  roles:
    - pre
    - dotfiles
    - caddy
    - 0x0i.systemd
    - { role: dev-sec.os-hardening, become: yes }
    - { role: dev-sec.ssh-hardening, become: yes }
