---
#- hosts: gcn
- hosts: default
  collections:
    - devsec.hardening
  vars:
    #    flutter_dir: '/opt/flutter'
    ssh_custom_options:
      - "Include /etc/ssh/ssh_config.d/*"
    sshd_custom_options:
      - "AcceptEnv LANG"
    dotfiles_user_dir: "/home/ops"
    dotfiles_user_name: "ops"
    maintemplate_user_name: "ops"
    maintemplate_bind_mount_dir: '/var/www/org-y'
    victoriametrics_version: "v1.51.0"
  roles:
    - pre
    - dotfiles
    - caddy
    - maintemplate
    - { role: ansible-victoriametrics-role, become: yes }
    - { role: os_hardening, become: yes }
    - { role: ssh_hardening, become: yes }
