name: build-v2

on:
  pull_request:
    branches:
      - "master"

jobs:
  all:
    name: build-v2
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ 1.15.6 ]
        target: [ "v2", ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Setup Go binary path
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Git line endings
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out main code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

      - name: Check out the sys-share code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: getcouragenow/sys-share
          path: ${{ github.workspace }}/go/src/github.com/gutterbacon/sys-share

      - name: Check out the mod code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: getcouragenow/mod
          path: ${{ github.workspace }}/go/src/github.com/gutterbacon/mod

      - name: Check out the sys code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: getcouragenow/sys
          path: ${{ github.workspace }}/go/src/github.com/gutterbacon/sys


      - name: make ${{ matrix.target }}
        run: |
          # workaround for https://github.com/actions/setup-go/issues/14
          #export GOPATH=${GITHUB_WORKSPACE}/go
          #export PATH=$PATH:$GOPATH/bin
          make $target
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
        env:
          CONFIG_PASSWORD: ${{ secrets.CONFIG_PASSWORD }}
          target: ${{ matrix.target }}

