# fly.toml file generated for withered-morning-8272 on 2020-12-14T05:32:51Z

app = "withered-morning-8272"


[[services]]
  internal_port = 9074
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
